apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
  source:
    repoURL: https://firefly-iii.github.io/kubernetes/
    chart: firefly-iii-stack
    targetRevision: 0.9.0       # specific chart version
    helm:
      releaseName: firefly-iii
      values: |
        firefly-db:
          storage:
            accessModes: ["ReadWriteOnce"]
            size: 2Gi
            existingClaim: firefly-pvc-postgres 
          image:
            tag: 10-alpine
          backup:
            pvc: 
              existingClaim: firefly-db-backup
          configs:
            existingSecret: firefly-iii-secret-db
            DBNAME: firefly

        firefly-iii:
          image:
            tag: latest
          service:
            type: NodePort
          config:
            existingSecret: firefly-iii-secret
            TRUSTED_PROXIES: "**"
          env:
            DB_CONNECTION: pgsql
          persistence:
            enabled: true
            storageClass: synology-nfs
            size: 1Gi
            existingClaim: firefly-pvc

        importer:
          # -- Set to false to not deploy the importer
          enabled: true

          service:
            type: NodePort

          config:
              env:
                FIREFLY_III_UR: "http://192.168.1.241:31148"

          fireflyiii:
          # -- The URL at which Firefly III is available. If you change this value, click the "Reauthenticate" button on the importer after opening it!
            url: "http://192.168.1.241:31148"
            vanityUrl: "http://192.168.1.241:31148"
            

        
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firefly-iii-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/callm23/argocd.git   # dein Git Repo
    targetRevision: main                                # Branch oder Tag
    path: applications/firefly-iii                                # Ordner im Repo
  destination:
    server: https://kubernetes.default.svc
    namespace: firefly-iii
  syncPolicy:
    automated:
      prune: true       # löscht nicht mehr vorhandene Objekte
      selfHeal: true    # korrigiert manuelle Änderungen