apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts  # Helm chart repository
    chart: k8s-monitoring                                 # Chart name
    targetRevision: 3.4.2                             # Chart version
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true       # Deletes resources no longer defined in the chart
      selfHeal: true    # Corrects manual changes to resources