apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/callm23/argocd.git   # dein Git Repo
    targetRevision: main                                # Branch oder Tag
    path: applications/grafana                                 # Ordner im Repo
    directory:
      recurse: true  # Enable recursive search for manifests in sub-folders
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true       # löscht nicht mehr vorhandene Objekte
      selfHeal: true    # korrigiert manuelle Änderungen
