apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts  # Helm chart repository
    chart: k8s-monitoring                                 # Chart name
    targetRevision: 3.4.2                             # Chart version
    helm:
      valuesObject:
        cluster:
          name: as03
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              usernameKey: auth.username
              passwordKey: auth.password
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-012.grafana.net./loki/api/v1/push
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              usernameKey: auth.username
              passwordKey: auth.password
        clusterMetrics:
          enabled: true
        clusterEvents:
          enabled: true
        nodeLogs:
          enabled: false
        podLogs:
          enabled: true
        alloy-metrics:
          enabled: false
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-auth
                    key: auth.password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: false
        alloy-singleton:
          enabled: false
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-auth
                    key: auth.password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
           enabled: false
        alloy-logs:
          enabled: false
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-auth
                    key: auth.password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
          remoteConfig:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true       # Deletes resources no longer defined in the chart
      selfHeal: true    # Corrects manual changes to resources