apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated:
      prune: true       # Deletes resources no longer defined in the chart
      selfHeal: true    # Corrects manual changes to resources
  source:
    repoURL: https://grafana.github.io/helm-charts  # Helm chart repository
    chart: k8s-monitoring                                 # Chart name
    targetRevision: 3.4.2                             # Chart version
    helm:
      valuesObject:
        cluster:
          name: as03
        destinations:
          - name: grafana-cloud-metrics
            type: prometheus
            url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom/push
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              username: "2675015"
              passwordKey: auth.password
          - name: grafana-cloud-logs
            type: loki
            url: https://logs-prod-012.grafana.net./loki/api/v1/push
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              username: "1333184"
              passwordKey: auth.password
          - name: gc-otlp-endpoint
            type: otlp
            url: https://otlp-gateway-prod-eu-west-2.grafana.net./otlp
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            protocol: http
            auth:
              type: basic
              username: "1375390"
              passwordKey: auth.password
            metrics:
              enabled: true
            logs:
              enabled: true
            traces:
              enabled: true
        clusterMetrics:
          enabled: true
          opencost:
            enabled: true
            metricsSource: grafana-cloud-metrics
            opencost:
              exporter:
                defaultClusterId: as03
              prometheus:
                existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                external:
                  url: https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom
          kepler:
            enabled: true
        clusterEvents:
          enabled: true
        podLogs:
          enabled: true
        applicationObservability:
          enabled: true
          receivers:
            otlp:
              grpc:
                enabled: true
                port: 4317
              http:
                enabled: true
                port: 4318
            zipkin:
              enabled: true
              port: 9411
        alloy-metrics:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: as03
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-011.grafana.net
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              username: "1375390"
              passwordKey: auth.password
        alloy-singleton:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: as03
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-011.grafana.net
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              username: "1375390"
              passwordKey: auth.password
        alloy-logs:
          enabled: true
          alloy:
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: alloy-logs-remote-cfg-grafana-k8s-monitoring
                    key: password
              - name: CLUSTER_NAME
                value: as03
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-011.grafana.net
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              username: "1375390"
              passwordKey: auth.password
        alloy-receiver:
          enabled: true
          alloy:
            extraPorts:
              - name: otlp-grpc
                port: 4317
                targetPort: 4317
                protocol: TCP
              - name: otlp-http
                port: 4318
                targetPort: 4318
                protocol: TCP
              - name: zipkin
                port: 9411
                targetPort: 9411
                protocol: TCP
            extraEnv:
              - name: GCLOUD_RW_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: grafana-cloud-auth
                    key: alloy.password
              - name: CLUSTER_NAME
                value: my-cluster
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: GCLOUD_FM_COLLECTOR_ID
                value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
          remoteConfig:
            enabled: true
            url: https://fleet-management-prod-011.grafana.net
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            secret:
              create: false
              name: grafana-cloud-auth
              namespace: grafana
            auth:
              type: basic
              usernameKey: otlp.username
              passwordKey: auth.password