apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/callm23/argocd.git   # dein Git Repo
    targetRevision: main                                # Branch oder Tag
    path: applications/prometheus                                 # Ordner im Repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true       # löscht nicht mehr vorhandene Objekte
      selfHeal: true    # korrigiert manuelle Änderungen
