---
# Source: k8s-monitoring/charts/alloy-operator/templates/rbac/leader-election.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-k8s-monitoring-alloy-operator-leader-election-role
  namespace: grafana
  labels:
    helm.sh/chart: alloy-operator-0.3.9
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.2.1"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
# Source: k8s-monitoring/charts/alloy-operator/templates/rbac/leader-election.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-k8s-monitoring-alloy-operator-leader-election-rolebinding
  namespace: grafana
  labels:
    helm.sh/chart: alloy-operator-0.3.9
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.2.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-k8s-monitoring-alloy-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: grafana-k8s-monitoring-alloy-operator
    namespace: grafana
