apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: homeassistant-config
  namespace: monitoring
  labels:
    app: prometheus
spec:
  scrapeConfigSelector:
    matchLabels:
      app: prometheus
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - http://192.168.1.235:8123/api/prometheus
