apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: homeassistant-config
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - 192.168.1.235:8123/api/prometheus
  httpSDConfigs:
    - url: http://192.168.1.235:8123/api/prometheus
      refreshInterval: 15s