apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-synology-pvc
  namespace: monitoring
spec:
  volumeName: nfs-pv-synology
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi