---
# Source: k8s-monitoring/charts/clusterMetrics/charts/opencost/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-k8s-monitoring-opencost
  labels:
    helm.sh/chart: opencost-2.2.7
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.117.3"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-k8s-monitoring-opencost
subjects:
  - kind: ServiceAccount
    name: grafana-k8s-monitoring-opencost
    namespace: grafana
