---
# Source: k8s-monitoring/charts/clusterMetrics/charts/opencost/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-k8s-monitoring-opencost
  namespace: grafana
  labels:
    helm.sh/chart: opencost-2.2.7
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.117.3"
    app.kubernetes.io/part-of: opencost
    app.kubernetes.io/managed-by: Helm
  annotations:
    checksum/configs: 930260623d85bc2f803e4342c37094e5e1f9ba8b76314664d4abc01dca140c56
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opencost
      app.kubernetes.io/instance: grafana-k8s-monitoring
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opencost
        app.kubernetes.io/instance: grafana-k8s-monitoring
    spec:
      serviceAccountName: grafana-k8s-monitoring-opencost
      automountServiceAccountToken: true
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: arm64
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: grafana-k8s-monitoring-opencost
          image: ghcr.io/opencost/opencost:1.117.3@sha256:09fae89c4544ec2a891e2902e88ce3137d7032c6edbe0fd97441aaee7bdbea54
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - containerPort: 9003
              name: http
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 55Mi
          startupProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: LOG_LEVEL
              value: info
            - name: CUSTOM_COST_ENABLED
              value: "false"
            - name: INSTALL_NAMESPACE
              value: default
            - name: PROMETHEUS_QUERY_RESOLUTION_SECONDS
              value: "300"
            - name: API_PORT
              value: "9003"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "https://prometheus-prod-24-prod-eu-west-2.grafana.net./api/prom"
            - name: INSECURE_SKIP_VERIFY
              value: "false"
            - name: CLUSTER_ID
              value: "my-cluster"
            - name: DB_BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-metrics-grafana-k8s-monitoring
                  key: username
            - name: DB_BASIC_AUTH_PW
              valueFrom:
                secretKeyRef:
                  name: grafana-cloud-metrics-grafana-k8s-monitoring
                  key: password
            - name: RESOLUTION_1D_RETENTION
              value: "15"
            - name: RESOLUTION_1H_RETENTION
              value: "49"
            - name: CLOUD_COST_ENABLED
              value: "false"
            - name: CLOUD_COST_MONTH_TO_DATE_INTERVAL
              value: "6"
            - name: CLOUD_COST_REFRESH_RATE_HOURS
              value: "6"
            - name: CLOUD_COST_QUERY_WINDOW_DAYS
              value: "7"
            - name: CLOUD_COST_RUN_WINDOW_DAYS
              value: "3"
            - name: EMIT_KSM_V1_METRICS
              value: "false"
            - name: EMIT_KSM_V1_METRICS_ONLY
              value: "true"
            # Add any additional provided variables
            - name: CLOUD_PROVIDER_API_KEY
              value: "AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U"
            - name: CURRENT_CLUSTER_ID_FILTER_ENABLED
              value: "true"
            - name: PROM_CLUSTER_ID_LABEL
              value: "cluster"
