apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
   - 192.168.5.10-192.168.5.100   # IP-Range aus deinem LAN
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advert1
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
