---
# Paperless-ngx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  namespace: paperless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      securityContext:
        fsGroup: 1000  # <-- matches paperless GID
      serviceAccountName: default
      containers:
        - name: paperless
          image: paperlessngx/paperless-ngx:2.20.6
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: PAPERLESS_REDIS
              value: redis://redis-svc:6379
            - name: PAPERLESS_DBHOST
              value: postgres-svc
            - name: PAPERLESS_DBUSER
              value: paperless
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: paperless-db-secret
                  key: POSTGRES_PASSWORD
            - name: PAPERLESS_DBNAME
              value: paperless
            - name: PAPERLESS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: paperless-db-secret
                  key: PAPERLESS_SECRET_KEY
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/consume
              name: consume
            - mountPath: /usr/src/paperless/import
              name: import
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: consume
          persistentVolumeClaim:
            claimName: paperless-consume
        - name: import
          persistentVolumeClaim:
            claimName: paperless-import
---
# Service für Paperless
apiVersion: v1
kind: Service
metadata:
  name: paperless-svc
  namespace: paperless
spec:
  type: NodePort
  selector:
    app: paperless
  ports:
    - port: 80
      targetPort: 8000