---
# Source: paperless/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paperless
  labels:
    helm.sh/chart: paperless-5.2.0
    app.kubernetes.io/name: paperless
    app.kubernetes.io/instance: paperless
    app.kubernetes.io/version: "2.17.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paperless
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
