apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: paperless
spec:
  provider:
    vault:
      server: "http://openbao:8200"
      path: "secret/data/bla"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
