---
# Source: openbao/templates/injector-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openbao-agent-injector-svc
  namespace: default
  labels:
    app.kubernetes.io/name: openbao-agent-injector
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
  
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: openbao-agent-injector
    app.kubernetes.io/instance: openbao
    component: webhook
