---
# Source: openbao/templates/server-headless-service.yaml
# Service for OpenBao cluster
apiVersion: v1
kind: Service
metadata:
  name: openbao-internal
  namespace: default
  labels:
    helm.sh/chart: openbao-0.16.2
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
    openbao-internal: "true"
  annotations:

spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: "http"
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
    component: server
