---
# Source: openbao/templates/server-config-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: openbao-config
  namespace: default
  labels:
    helm.sh/chart: openbao-0.16.2
    app.kubernetes.io/name: openbao
    app.kubernetes.io/instance: openbao
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    
    ui = true
    
    listener "tcp" {
      tls_disable = 1
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      #telemetry {
      #  unauthenticated_metrics_access = "true"
      #}
    }
    storage "file" {
      path = "/openbao/data"
    }
    
    # Example configuration for using auto-unseal, using Google Cloud KMS. The
    # GKMS keys must already exist, and the cluster must have a service account
    # that is authorized to access GCP KMS.
    #seal "gcpckms" {
    #   project     = "openbao-helm-dev"
    #   region      = "global"
    #   key_ring    = "openbao-helm-unseal-kr"
    #   crypto_key  = "openbao-helm-unseal-key"
    #}
    
    # Example configuration for enabling Prometheus metrics in your config.
    #telemetry {
    #  prometheus_retention_time = "30s"
    #  disable_hostname = true
    #}
