apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-vault-cluster-store
spec:
  provider:
    vault:
      server: "http://openbao:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
          namespace: paperless