apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allow-net-raw
spec:
  privileged: false
  allowedCapabilities:
    - NET_RAW
  volumes:
    - '*'
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny