apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-synology-1
  labels:
    app.kubernetes.io/name: my-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: /volume2/proxmox/kubernetes/nfs/prometheus-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-synology-2
  labels:
    app.kubernetes.io/name: my-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: /volume2/proxmox/kubernetes/nfs/prometheus-2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vault
  labels:
    app.kubernetes.io/name: my-vault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: /volume2/proxmox/kubernetes/nfs/vault
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs
provisioner: example.com/external-nfs
parameters:
  server: 192.168.1.100
  path: /volume2/proxmox/kubernetes/nfs/vault
  readOnly: "false"
---
