apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-synology
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.100
    path: /volume2/proxmox/kubernetes/nfs
  persistentVolumeReclaimPolicy: Retain