apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-synology
  labels:
    app.kubernetes.io/name: my-prometheus
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.100
    path: /volume2/proxmox/kubernetes/nfs
  persistentVolumeReclaimPolicy: Retain