---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: immich/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: immich/postgres
        property: password
    - secretKey: POSTGRES_DB
      remoteRef:
        key: immich/postgres
        property: database