---
# Source: k8s-monitoring/charts/alloy-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-k8s-monitoring-alloy-operator
  namespace: grafana
  labels:
    helm.sh/chart: alloy-operator-0.3.9
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "1.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy-operator
      app.kubernetes.io/instance: grafana-k8s-monitoring
  template:
    metadata:
      labels:
        helm.sh/chart: alloy-operator-0.3.9
        app.kubernetes.io/name: alloy-operator
        app.kubernetes.io/instance: grafana-k8s-monitoring
        app.kubernetes.io/version: "1.2.1"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: grafana-k8s-monitoring-alloy-operator
      containers:
        - name: alloy-operator
          image: "ghcr.io/grafana/alloy-operator:1.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8082
            - --leader-elect
            - --leader-election-id=grafana-k8s-monitoring-alloy-operator

          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 8082
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits: {}
            requests: {}
          securityContext:
            runAsNonRoot: true
      nodeSelector:
        kubernetes.io/os: linux
