---
# Source: k8s-monitoring/charts/autoInstrumentation/charts/beyla/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-k8s-monitoring-beyla
  namespace: grafana
  labels:
    helm.sh/chart: beyla-1.9.4
    app.kubernetes.io/name: beyla
    app.kubernetes.io/instance: grafana-k8s-monitoring
    app.kubernetes.io/version: "2.6.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: beyla
    app.kubernetes.io/component: rbac
automountServiceAccountToken: true
