apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-cloud-ingest-bao
  namespace: grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-vault-cluster-store
    kind: ClusterSecretStore
  target:
    name: grafana-cloud-ingest-bao
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: secret/data/firefly-iii
        property: MYSQL_DATABASE
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: secret/data/firefly-iii
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: secret/data/firefly-iii
        property: metrics.username
    - secretKey: MYSQL_USER
      remoteRef:
        key: secret/data/firefly-iii
        property: MYSQL_USER